### ISSUE TITLE
CLI node error

### ISSUE THREAD

**Issue by laurentpayot** [terser/html-minifier-terser#74]
**html-minifier-terser version: 6.0.1
OS: Ubuntu 21.04**

On node 14.0.0 _and above_  if I use the following command:
```
npx --package node@14.0.0 -- html-minifier-terser --file-ext html --input-dir src --output-dir dist
```
I get:
```
internal/fs/utils.js:656
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Promise
    at Object.writeFile (fs.js:1356:5)
    at /home/laurent/projects/myproject/node_modules/html-minifier-terser/cli.js:245:8
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3) {
  code: 'ERR_INVALID_ARG_TYPE'
}
``` 

On node 13.14.0 the following command generates no error:
```
npx --package node@13.14.0 -- html-minifier-terser --file-ext html --input-dir src --output-dir dist
```
but the content of the minified html file is:
```
 [object Promise]
```

Everything was working fine with html-minifier-terser v5.1.1

**Comment by DanielRuf** [comment]
Can you provide a PR and test it with different test cases? That would be great.

See also https://github.com/terser/html-minifier-terser/commit/4d03536ca555b8f5034441a4ef27744f7b7ec650

**Comment by laurentpayot** [comment]
@DanielRuf  I just found out that  the simpler command line `html-minifier-terser src/index.html -o dist/index.html` is working. 
The culprit must be the `--input-dir`/`--output-dir` options.

**Comment by DanielRuf** [comment]
> html-minifier-terser/cli.js:245:8

Yes, see this line where no async / await is used:

https://github.com/terser/html-minifier-terser/blob/master/cli.js#L240

And compare it to this:

https://github.com/terser/html-minifier-terser/blob/master/cli.js#L281

**Comment by sibiraj-s** [comment]
We definitely need tests for this cli file.

**Comment by DanielRuf** [comment]
> We definitely need tests for this cli file.

Definitely, see also https://github.com/terser/html-minifier-terser/issues/33

Personally I am not investing much time in opensource anymore due to personal reasons so if anyone wants to help that would be great.

**Comment by sibiraj-s** [comment]
I would love to help out.

**Comment by laurentpayot** [comment]
Created PR #75

**Comment by DanielRuf** [comment]
html-minifier-terser v6.0.2 has been released and the issue in the CLI should be fixed now.

Thanks for reporting the issue and thanks for the PR to fix this.
If this issue is still not resolved, please let me know and I will reopen this issue.

Not sure what the best solution is to test the CLI.

**Comment by sibiraj-s** [comment]
> Not sure what the best solution is to test the CLI.

To start with, we don't need to test the entire cli, we can split the processing part into separate modules/files and test them alone.
